### ISSUE TITLE
启动Docker镜像步骤的时候 报错

### ISSUE THREAD

**Issue by 1998yyh** [LiushuiXiaoxia/docker-osx#1]
启动Docker镜像步骤的时候 报错：

KVM: entry failed, hardware error 0x80000021

If you're running a guest on an Intel machine without unrestricted mode
support, the failure can be most likely due to the guest entering an invalid
state for Intel VT. For example, the guest maybe running in big real mode
which is not supported on less recent Intel processors.

网上搜了一下也没什么好的解决方案，请问您有办法解决吗

**Comment by LiushuiXiaoxia** [comment]
需要开启cpu虚拟化 ，搜索一下关键字 Intel VT 。
最好使用intel的cup，amd的估计有坑。
